### ISSUE TITLE
Tamalib on its way to run in Retro-go on the Game & Watch Mario & Zelda Edition

### ISSUE THREAD

**Issue by BenjaminSoelberg** [jcrona/tamalib#15]
Hi I just wanted to let you know that I have successfully 'ported' your fantastic lib to a new emulator for the Nintendo Game & Watch system. It was great fun, and thank you for making tamalib. I have incorporated some changes, mostly to suit the needs of Retro-Go. I have also added a 'fast-forward' function to emulate the 'always on' functionality so the emulator can catch up upon repower on. I added an instruction decoding cache to aid this and make the tamagotchi as fast as possible. It can now run about 300% faster (above 8000fps on my device) when needed.

Thank you again for making this emulator.
My fork can be found here:
https://github.com/BenjaminSoelberg/tamalib
And the retro go code here:
https://github.com/BenjaminSoelberg/game-and-watch-retro-go/tree/tamagotchi/Core/Src/porting/tama
A PR to incorporate it into the main branch of retro-go is on its way.

**Comment by jcrona** [comment]
So cool @BenjaminSoelberg \o/ !
